
splunkforwarderpackage: "splunkforwarder-{{ splunkforwarderversion }}-linux-2.6-x86_64.rpm"
splunkforwardermanifest: "/opt/splunkforwarder/splunkforwarder-{{ splunkforwarderversion }}-linux-2.6-x86_64-manifest"

